spring:
  application:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dhumbal?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: subedisunil495@gmail.com
    password: "zabg bpua tmzg ntca"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    enabled: true
    docExpansion: none # list, full, none
dhumbal:
  server:
    url: http://localhost:8080
  security:
    corsAllowedOrigins: "http://localhost:5173"
    corsAllowedMethods: "GET,POST,PUT,PATCH,DELETE"
    permitUrls: "/dhumbal-websocket,/v1/user/verify/**,/v1/auth/register,/v1/auth/login,/v1/auth/google,/v1/auth/guest,/v1/auth/token/refresh,/swagger-ui.html,/v3/api-docs,/v3/api-docs/*,/swagger-ui/*"
    jwt:
      key: IesVMpepKO+d6cRtSeQH7uVrHofuRfJYagh+erVJg/xGs4jnJQU6oox04+eoD8CtRZviXafLYkpQrg73d1pqBg==
      accessTokenExpiryInMinute: 30
      refreshTokenExpiryInMinute: 43200
    google:
      certUrl: https://www.googleapis.com/oauth2/v3/certs
      clientId: 24099078143-qq0hgilb233dmasq45klcqdt36kthlnm.apps.googleusercontent.com
    otp:
      expiry: 60
      length: 15
  room:
    code:
      length: 5
    member:
      max: 4
  game:
    points:
      multiplier: 10
    card:
      count: 7

